kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '6'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"books-api:latest","namespace":"book-library"},"fieldPath":"spec.template.spec.containers[?(@.name==\"books-api\")].image","pause":"true"}]
    kubectl.kubernetes.io/last-applied-configuration: >-
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"image.openshift.io/triggers":"[{\"from\":{\"kind\":\"ImageStreamTag\",\"name\":\"books-api:latest\"},\"fieldPath\":\"spec.template.spec.containers[?(@.name==\\\"books-api\\\")].image\"}]","openshift.io/generated-by":"OpenShiftNewApp"},"creationTimestamp":null,"labels":{"app":"books-api","app.kubernetes.io/component":"books-api","app.kubernetes.io/instance":"books-api"},"name":"books-api","namespace":"book-library"},"spec":{"replicas":1,"selector":{"matchLabels":{"deployment":"books-api"}},"strategy":{},"template":{"metadata":{"annotations":{"openshift.io/generated-by":"OpenShiftNewApp"},"creationTimestamp":null,"labels":{"deployment":"books-api"}},"spec":{"containers":[{"image":"
      ","name":"books-api","ports":[{"containerPort":8080,"protocol":"TCP"}],"resources":{}}]}}},"status":{}}
    openshift.io/generated-by: OpenShiftNewApp
  resourceVersion: '984715'
  name: books-api
  uid: 2faf748f-3624-4055-b2b5-1f93981bbbc2
  creationTimestamp: '2022-12-20T05:34:01Z'
  generation: 6
  managedFields:
    - manager: OpenAPI-Generator
      operation: Update
      apiVersion: apps/v1
      time: '2022-12-30T06:24:40Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:image.openshift.io/triggers': {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:replicas': {}
          'f:revisionHistoryLimit': {}
          'f:selector': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:annotations':
                .: {}
                'f:openshift.io/generated-by': {}
              'f:labels':
                .: {}
                'f:deployment': {}
            'f:spec':
              'f:containers':
                'k:{"name":"books-api"}':
                  .: {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":8080,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                  'f:resources': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2022-12-30T06:24:41Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:template':
            'f:spec':
              'f:containers':
                'k:{"name":"books-api"}':
                  'f:image': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2022-12-31T15:09:27Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:updatedReplicas': {}
      subresource: status
  namespace: book-library
  labels:
    app: books-api
    app.kubernetes.io/component: books-api
    app.kubernetes.io/instance: books-api
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: books-api
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: books-api
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: books-api
          image: >-
            quay.io/redhattraining/books-api@sha256:6b19f5c3c09ada67023609f79bc70717174f17c974603c42a44f10a158831058
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      imagePullSecrets: []
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  paused: false
status:
  observedGeneration: 6
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2022-12-20T05:34:25Z'
      lastTransitionTime: '2022-12-20T05:34:01Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "books-api-5cb6b5797" has successfully progressed.
    - type: Available
      status: 'True'
      lastUpdateTime: '2022-12-31T15:09:27Z'
      lastTransitionTime: '2022-12-31T15:09:27Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
